[run]
# n_steps = 100000
t_stop = 0.02
# t_wall_stop = 3.0
# dt = 1.0e-5
cfl = 1.0

[mesh]
type = "wedge"
Nx = 160
Ny = 120
Lx = 2.0
Ly = 1.5

[initialize]
type = "constant"
u = [600.0, 0.0]
p = 101325.0
T = 300.0

[[boundaries]]
name = "left"
type = "upt"
u = [600.0, 0.0]
p = 101325.0
T = 300.0
# type = "symmetry"

[[boundaries]]
name = "right"
type = "p_out"
p = 101325.0
# type = "symmetry"

[[boundaries]]
name = "top"
type = "symmetry"

[[boundaries]]
name = "bottom"
type = "symmetry"

[numerics]
riemann_solver = "HLLC"
time_integrator = "SSPRK3"
check_nan = false

[numerics.face_reconstruction]
type = "MUSCL"
limiter = "venkatakrishnan"

[physics]
type = "euler"
gamma = 1.4
p_ref = 101325.0
T_ref = 298.15
rho_ref = 1.225
# p_max = 1e20

[output]
check_interval = 100

[[write_data]]
prefix = "./solut/wedge"
format = "vtu"
time_interval = 0.0005
variables = ["RHO", "U_X", "U_Y", "P", "T"]
