[run]
# n_steps = 100000
t_stop = 0.1
# t_wall_stop = 3.0
# dt = 1.0e-5
cfl = 1.0

[mesh]
type = "wedge"
Nx = 150
Ny = 50
Lx = 4
Ly = 1.5

[initialize]
type = "constant"
u = [600.0, 0.0]
p = 101325.0
T = 300.0

[[boundaries]]
name = "left"
type = "upt"
u = [600.0, 0.0]
p = 101325.0
T = 300.0
# type = "symmetry"

[[boundaries]]
name = "right"
type = "p_out"
p = 101325.0
# type = "symmetry"

[[boundaries]]
name = "top"
type = "symmetry"

[[boundaries]]
name = "bottom"
type = "symmetry"

[numerics]
face_reconstruction = "FO"
riemann_solver = "HLLC"
time_integrator = "SSPRK3"
check_nan = false
check_nan_flux = false

[physics]
type = "euler"
gamma = 1.4
p_ref = 101325.0
T_ref = 298.15
rho_ref = 1.225
p_min = 1.0e-6
# p_max = 1e20

[output]
check_interval = 100

[[write_data]]
prefix = "./solut/all/wedge_all"
format = "vtu"
geometry = "all"
interval = 1000
variables = ["CFL", "RHO", "RHOU_X", "RHOU_Y", "RHOE", "U_X",  "U_Y", "P", "T", "H"]
