[run]
# n_steps = 100000
t_stop = 0.3
# t_wall_stop = 3.0
# dt = 1.0e-5
cfl = 0.1

[mesh]
type = "cartesian_tri"
Nx = 1024
Ny = 1024
Lx = 1.0
Ly = 1.0

[initialize]
type = "analytical"
rho = """\
    var l := x <  0.8; \
    var r := x >= 0.8; \
    var b := y <  0.8; \
    var t := y >= 0.8; \
    1.5 * r * t + 0.532258064516129 * l * t \
                + 0.137992831541219 * l * b \
                + 0.532258064516129 * r * b"""
u = [
    """\
    var l := x <  0.8; \
    var r := x >= 0.8; \
    var b := y <  0.8; \
    var t := y >= 0.8; \
    0.0 * r * t + 1.206045378311055 * l * t \
                + 1.206045378311055 * l * b \
                + 0.0               * r * b""",
    """\
     var l := x <  0.8; \
     var r := x >= 0.8; \
     var b := y <  0.8; \
     var t := y >= 0.8; \
     0.0 * r * t + 0.0               * l * t \
                 + 1.206045378311055 * l * b \
                 + 1.206045378311055 * r * b"""
]
p = """\
    var l := x <  0.8; \
    var r := x >= 0.8; \
    var b := y <  0.8; \
    var t := y >= 0.8; \
    1.5 * r * t + 0.3 * l * t + 0.029032258064516 * l * b + 0.3 * r * b"""

[[boundaries]]
name = "left"
type = "symmetry"

[[boundaries]]
name = "right"
type = "symmetry"

[[boundaries]]
name = "top"
type = "symmetry"

[[boundaries]]
name = "bottom"
type = "symmetry"

[numerics]
face_reconstruction = "TENO"
riemann_solver = "HLLC"
time_integrator = "SSPRK3"
check_nan = true

[numerics.TENO]
basis = "legendre"
basis_order = 3
quadrature = "triangle_dunavant"
quadrature_order = 3
max_stencil_size_factor = 2.0

[physics]
type = "euler"
gamma = 1.4
p_ref = 101325.0
T_ref = 298.15
rho_ref = 1.225

[output]
check_interval = 100

[[write_data]]
prefix = "./solut/all/riemann_all"
format = "vtu"
geometry = "all"
interval = 100
variables = ["CFL", "RHO", "RHOU_X", "RHOU_Y", "RHOE", "U_X",  "U_Y", "P", "T", "H"]
