# (header written with the results)

[run]
t_stop = 4.0e-6
cfl = 0.5

[mesh]
type = "cartesian"
Nx = 704
Ny = 127
Nz = 127
Lx = 9.9e-4
Ly = 1.7859375e-4
Lz = 1.7859375e-4

[initialize]
type = "restart"
file = "init.restart"

[[boundaries]]
name = "left"
type = "upt"
u = [129.682, 0.0, 0.0]
p = 167966.887
T = 341.939
Y = { N2 = 0.767, O2 = 0.233 }

[[boundaries]]
name = "right"
type = "extrapolation"

[[boundaries]]
name = "bottom"
type = "symmetry"

[[boundaries]]
name = "back"
type = "symmetry"

[[boundaries]]
name = "top"
type = "symmetry"

[[boundaries]]
name = "front"
type = "symmetry"

[numerics]
riemann_solver = "HLLC"
time_integrator = "SSPRK3"
double_flux = false

[numerics.face_reconstruction]
type = "MUSCL"

[physics]
type = "navier_stokes"
gas = "mixture"
mechanism = "../../mechanisms/he_air.yaml"
transport = "mixture_averaged"

[output]
check_interval = 100

[[probes]]
name = "axis"
variables = ["RHO", "U_X", "P", "Y_HE"]
start = [7.03125e-7, 1.0e-9, 1.0e-9]
end = [9.89296875e-4, 1.0e-9, 1.0e-9]
n_points = 704
interval = 50

[[write_data]]
prefix = "./restart/bubble"
format = "restart"
time_interval = 4.0e-8
