[run]
# n_steps = 100000
t_stop = 0.2
# t_wall_stop = 3.0
# dt = 1.0e-3
cfl = 1.0

[mesh]
type = "cartesian"
Nx = 1000
Ny = 1
Lx = 1.0
Ly = 0.001

[initialize]
type = "analytical"
rho = """\
    var l := x <  0.5; \
    var r := x >= 0.5; \
    1.0 * l + 0.125 * r"""
u = ["0.0", "0.0"]
p = """\
    var l := x <  0.5; \
    var r := x >= 0.5; \
    1.0 * l + 0.1 * r"""

[[boundaries]]
name = "left"
# type = "symmetry"
type = "extrapolation"

[[boundaries]]
name = "right"
# type = "symmetry"
type = "extrapolation"

[[boundaries]]
name = "top"
# type = "symmetry"
type = "extrapolation"

[[boundaries]]
name = "bottom"
# type = "symmetry"
type = "extrapolation"

[numerics]
face_reconstruction = "FO"
riemann_solver = "HLLC"
time_integrator = "SSPRK3"
check_nan = true
check_nan_flux = true

[physics]
type = "euler"
gamma = 1.4
p_ref = 101325.0
T_ref = 298.15
rho_ref = 1.225
# p_min = 1.0e-6
# p_max = 1.0e20

[output]
check_interval = 100

[[write_data]]
prefix = "./solut/all/sod_all"
format = "vtu"
geometry = "all"
interval = 100
variables = ["CFL", "RHO", "RHOU_X", "RHOU_Y", "RHOE", "U_X",  "U_Y", "P", "T", "H"]
